### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/avail_wheels#12]
avail_wheels does not show python 3.10 wheels.

**Comment by ccoulombe** [comment]
This is automatically done in https://github.com/ComputeCanada/avail_wheels/commit/332a6052f891a566235fd279efc1ce8113b45c8a which will come with version 2.0. 

I'll update it locally for the meantime.

**Comment by mboisson** [comment]
I added comments in the commit. That commit won't work for python 3.10

**Comment by ccoulombe** [comment]
Fixed locally. 
I'll keep it open for tracking purpose with the coming release of v2

**Comment by ccoulombe** [comment]
This was finalized in 07ea5e3, aa20930
